### ISSUE TITLE
能否增加html页脚自定义编辑

### ISSUE THREAD

**Issue by lmm214** [soulteary/docker-flame#1]
备案号需要写上去……

**Comment by soulteary** [comment]
文章中有提，虽然很多 PR 提交给了 Flame，但是存在代码硬分叉，后续更新成本比较高，用户也比较少，暂时就不考虑更新了。

Flare 后续版本会添加一个 ICP 字段来展示信息进行合规。

**Comment by soulteary** [comment]
之前微信聊天有承诺过，flare v0.2.5 添加了这个功能，可以试试看 :) @lmm214 

https://github.com/soulteary/docker-flare/releases/tag/v0.2.5
