### ISSUE TITLE
“搜索”不能正常工作

### ISSUE THREAD

**Issue by Mantyke** [soulteary/docker-flame#2]
使用docker-compose部署，点开搜索页面后页面只显示页面底色

**Comment by soulteary** [comment]
你好👋，这里确实有一个小 Bug，虽然我已经修改了，但是因为 Docker CDN 缓存，似乎到现在都没有生效。

你可以手动修改数据目录的  `data/customQueries.json` ，将内容修改为下面这样：

```json
{ "queries": [] }
```

**Comment by Mantyke** [comment]
> 你好👋，这里确实有一个小 Bug，虽然我已经修改了，但是因为 Docker CDN 缓存，似乎到现在都没有生效。
> 
> 
> 
> 你可以手动修改数据目录的  `data/customQueries.json` ，将内容修改为下面这样：
> 
> 
> 
> ```json
> 
> { "queries": [] }
> 
> ```
已经修改过来了，非常感谢！
另外请教一下，考虑支持custom css吗？

**Comment by soulteary** [comment]
暂时不考虑继续基于 React + Node 的 Flame 提 PR了。

主要原因是我在用 flare 了，你可以试试“自定义页脚”功能，在里面加代码，不过我目前没有做在线编辑的功能，短时间也不考虑做在线编辑，因为体验不大可能有本地编辑器好。

https://github.com/soulteary/docker-flare

**Comment by Mantyke** [comment]
> 暂时不考虑继续基于 React + Node 的 Flame 提 PR了。
> 
> 主要原因是我在用 flare 了，你可以试试“自定义页脚”功能，在里面加代码，不过我目前没有做在线编辑的功能，短时间也不考虑做在线编辑，因为体验不大可能有本地编辑器好。
> 
> https://github.com/soulteary/docker-flare

明白了，我试用过flare，很喜欢它的轻便和便于备份，但是前端编辑对我来说是刚需（工作地点没有编辑文件的环境/前端编辑更方便随时随地加入想加入的书签），如果可以的话，还是期待能够加入前端编辑。
感谢！

**Comment by soulteary** [comment]
我想了想，好像确实应该有一个能够让人“随时随地”编辑的能力，我周末试试更新一个版本。 @Mantyke 

https://github.com/soulteary/docker-flare/issues/11

**Comment by soulteary** [comment]
已更新，添加了一个在线的编辑器（Excel 风格的编辑器，方便批量复制粘贴，以及拖动单元格批量复制），欢迎试用和提反馈，谢谢。 @Mantyke

**Comment by Mantyke** [comment]
> 已更新，添加了一个在线的编辑器（Excel 风格的编辑器，方便批量复制粘贴，以及拖动单元格批量复制），欢迎试用和提反馈，谢谢。 @Mantyke 

感谢！

**Comment by Mantyke** [comment]
> 已更新，添加了一个在线的编辑器（Excel 风格的编辑器，方便批量复制粘贴，以及拖动单元格批量复制），欢迎试用和提反馈，谢谢。 @Mantyke

反馈Bug：在前端编辑器中填写内容（仅填写站点名称、URL、分类）后，点击保存数据，编辑器变为下图
![image](https://user-images.githubusercontent.com/89439794/154854991-244e00e8-d880-4417-aef7-76d88635358b.png)
同时首页不显示编辑后内容（应该是没保存上）

**Comment by soulteary** [comment]
谢谢反馈，我明天把测试补了，看看问题在哪里。

**Comment by Mantyke** [comment]
> 谢谢反馈，我明天把测试补了，看看问题在哪里。

不知是否有帮助：我排查了一下，发现问题是不能出现空行。

**Comment by soulteary** [comment]
已修正，排查到原因不是空行，而是有一个叫做 Private 的属性，因为界面 “Excel” 隐藏了它，导致数值不正确，最终影响了存储和展示。

谢谢反馈，可以使用 0.2.10 版本试试看。

@Mantyke
